### ISSUE TITLE
Checkin/Checkout?

### ISSUE THREAD

**Issue by michis0806** [sirikon/timemoto-cli#1]
Hi @sirikon ,

thanks for your work. I'm currently trying to implement a simple Checkin/Checkout-function connected to timemoto for our employees in PHP. The script you're providing enabled me to get the auth-cookies and tokens and to submit the Form-data to  https://app.timemoto.com/ClockIn. But Checkin/Checkout currently does not work in this way. maybe I am just missing some form-data.

I was scraping the form-data from the webpage when logged in and got something like
```
<form action="/ClockIn" class="clockin timer clockinForm" method="post" role="form">
<input name="__RequestVerificationToken" type="hidden" value="_SOMEVALUE_">    <fieldset class="inner-height header">
...
    <input type="hidden" name="hideLatest" value="_SOMENUMBER_">
    <input type="hidden" name="hideLatestStatus" value="0">
    <input type="hidden" name="hideLatestWorkCode" value="">
    <input type="hidden" name="hideLatestLogId" value="_SOMEOTHERNUMBER_">
    <fieldset class="one-column footer">
        <a class="a-timer-logout" href="/Account/Logout?Close=True">Ausloggen</a>
    </fieldset>    
</form>
```
so my Post-content is
```
Array
(
    [__RequestVerificationToken] => _SOMEVALUE_
    [hideLatest] => _SOMENUMBER_
    [hideLatestStatus] => 0
    [hideLatestLogId] => _SOMEOTHERNUMBER_
)
```
And I'm setting the header
```
Array
(
    [0] => Cookie : __RequestVerificationToken=_SOMETOKEN_; cookie_consent_level=%7B%22strictly-necessary%22%3Atrue%2C%22functionality%22%3Atrue%2C%22tracking%22%3Atrue%2C%22targeting%22%3Atrue%7D; .AspNet.Cookies.Admin=_SOMECOOKIE_; cookie_consent_user_accepted: true
)
```
Authentication seems to work because I don't get any login-page as a response. But I don't get any action on checkin/checkout as well.

Do you happen to know what fields I'm missing?

Thanks a lot!
Michael

**Comment by sirikon** [comment]
Hi @michis0806 , glad to know my script was useful :smile: .

I don't know what fields are missing, need to continue investigating the Timemoto API and make it work for checkin/checkout. AFAIK, that subset of functionality is driven by a WebSockets connection, but that's all I know and I'm not 100% sure.

Good luck!

**Comment by michis0806** [comment]
Okay ;)
is there any documented API?

Michael

**Comment by sirikon** [comment]
AFAIK, no, I was just inspecting the network interactions with the browser's developer tools to figure things out :)

**Comment by michis0806** [comment]
Okay, I'm heading for the TimeMoto app with Charles Proxy, now ;)
